### ISSUE TITLE
Inconsistent Parsing Between YAML Config and Environment Variables for Nested Fields

### ISSUE THREAD

**Issue by sudiptob2** [G-Research/yunikorn-history-server#204]
We support configuration through both config files and environment variables (ENV vars). In the current implementation, it is not possible to define nested environment variables **beyond a single level** using ENV vars. Let's clarify this with an example.

Consider the following CORS configuration defined in YAML:

```yaml
yhs:
  port: 8989
  data_sync_interval: 20s
  cors:
    allowed_origins:
      - "*"
    allowed_methods:
      - "GET"
    allowed_headers:
      - "*"
```
If we want to define this using env vars, we would have to do something like the following:

```
YHS_YHS_CORS_ALLOWED_ORIGIN=*
...
```
`YHS_YHS_CORS_ALLOWED_ORIGIN` would be converted to yhs.cors_allowed_origin by the `processEnvVar()` function, but in the configuration file, it is read as `yhs.cors.allowed_origin`.

**As a result, the parsing of YAML and ENV vars is inconsistent.**

---
**Relevant code:**
https://github.com/G-Research/yunikorn-history-server/blob/ce8153c8910a898216d16d9fe3c97fbbf59bfe7d/internal/config/config.go#L173-L201
